### ISSUE TITLE
Pasting image doesn't work

### ISSUE THREAD

**Issue by techcap** [madskristensen/MarkdownEditor#129]
### Installed product versions
- Visual Studio: 2017 Enterprise 15.3.2
- This extension: 1.11.214

### Description
Pasting image doesn't work

### Steps to recreate
1. Copy image to clipboard
2. Paste on Markdown editor.
3. SaveFileDialog is open and select filename and save.
4. Error is occurred.

```
2017-08-24 오전 10:34:57: System.NullReferenceException: Object reference not set to an instance of an object.
   at MarkdownEditor.ProjectHelpers.IsKind(Project project, String[] kindGuids) in C:\projects\markdowneditor\src\Helpers\ProjectHelpers.cs:line 141
   at MarkdownEditor.ProjectHelpers.AddFileToProject(Project project, String file) in C:\projects\markdowneditor\src\Helpers\ProjectHelpers.cs:line 24
   at MarkdownEditor.PasteImage.SaveClipboardImageToFile(IDataObject data, String existingFile) in C:\projects\markdowneditor\src\Commands\PasteImageCommandTarget.cs:line 153
   at MarkdownEditor.PasteImage.Execute(VSStd97CmdID commandId, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut) in C:\projects\markdowneditor\src\Commands\PasteImageCommandTarget.cs:line 54
```

### Current behavior
Do not be pasted.

### Expected behavior
Should be generated image markdown.

**Comment by techcap** [comment]
I sent by email.

**Comment by techcap** [comment]
Did you test on vs 15.3.2? Befor updating to 15.3, there was no probleem. I'll try again on clean machine.

**Comment by techcap** [comment]
After reinstallation of VS, it is solved. Thanks.
