### ISSUE TITLE
System.ArgumentOutOfRangeException while editing

### ISSUE THREAD

**Issue by RalfKoban** [madskristensen/MarkdownEditor#196]
### Installed product versions
- Visual Studio: 2019 Enterprise 16.3.9
- This extension: 1.12.236

### Description
On occasion I get following error while editing (found inside Activity Monitor log):
```C#
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: length
   at Microsoft.VisualStudio.Text.Span..ctor(Int32 start, Int32 length)
   at MarkdownEditor.Outlining.MarkdownOutliningTagger.&lt;ProcessHeadingBlocks&gt;d__10.MoveNext() in C:\projects\markdowneditor\src\Outlining\MarkdownOutliningTagger.cs:line 137
   at System.Linq.Enumerable.&lt;UnionIterator&gt;d__67`1.MoveNext()
   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.&lt;GetTagsForBuffer&gt;d__47.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```
### Steps to recreate
Unfortunately it is unclear to me how to exactly reproduce it. The document seemed a longer one and I had ActiveSync disabled.

### Current behavior
Throwing exception during editing

### Expected behavior
Not throw an exception

**Comment by madskristensen** [comment]
This is fixed in the new preview extension https://marketplace.visualstudio.com/items?itemName=MadsKristensen.MarkdownEditor2
