### ISSUE TITLE
Unstable load/init of the extension?

### ISSUE THREAD

**Issue by xoofx** [madskristensen/MarkdownEditor#61]
Many times while loading the extension in the VS experimental hive while coding, I have been experienced an error that would make the MarkdownEditor not loadable anymore (I have to reset the experimental hive in this case). I have seen some people having the same trouble with some ActivityLog.xml (plus [a comment from the review NSH Brian](https://visualstudiogallery.msdn.microsoft.com/eaab33c3-437b-4918-8354-872dfe5d1bfe) on the VS Gallery, unfortunately, they should better report their problem here...)

My ActivityLog.xml has sometimes the following errors and after I cannot load the extension anymore... I haven't looked at other part of the extension. Is there anything special (async loading/init?) that could make this happen?

```
source: Microsoft.VisualStudio.CommonIDE.ExtensibilityHosting.VsShellComponentModelHost
description: A MEF Component threw an exception at runtime: System.Reflection.TargetParameterCountException: Parameter count mismatch.
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.CreateValue()
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.Create()
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveNext(PartLifecycleState nextState)
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveToState(PartLifecycleState requiredState)
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.GetValueReadyToExpose()
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.<>c__DisplayClass15_0.<GetExportedValueHelper>b__0()</description>
```

**Comment by madskristensen** [comment]
I see the same thing. Here's what works for me:

1. Clean solution, build solution, then (ctrl+)F5
2. If that doesn't work, up the version number in .vsixmanifest like 1.9._**12**_. Goto 1

Let me know if that works
